name: NPM Publish

on:
  push:
    tags:
      - '*'
jobs:
  npm-publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Update npm version
        run: npm version $VERSION --no-git-tag-version --allow-same-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ steps.get_tag.outputs.TAG }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
