name: Push Tags

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 16.x

jobs:
  push-tag:
    runs-on: ubuntu-latest
    name: Create new Git Tag on github

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get version from package.json
        id: get_tag
        run: echo ::set-output name=TAG::$(npm view . version)

      - name: Push Tag
        run: |
          tag=${{ steps.bump-semver.outputs.TAG }}
          message='New Version ${{ steps.get_tag.outputs.TAG }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
